# ----
# Site

title: Treat Template
url: "https://shellGrace.github.io/"
baseurl:
google_analytics_key:
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/shellGrace)
logo: /siteicon.png
description: Food blog template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Treat Template
  links:
    - https://github.com/shellGrace

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 0
          height: 0
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# shellGrace

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
